### ISSUE TITLE
Separate win/linux Dockerfiles

### ISSUE THREAD

**Issue by gandrein** [bigillu/ab-heartbyte#5]
Currently there is a single docker file with commented in/out lines for different host systems. 

As a windows based docker won't be run in production, I would propose to go for a production docker and one dev docker.  E.g. of Dockerfile structure see official doc
https://docs.docker.com/engine/reference/commandline/build/#specify-a-dockerfile--f

If Win-based docker is useful for development, then windows packages may be installed via a shell script based on OS type or again separate the dev image into two separate docker files and use use a multi-stage mechanism of docker for removing duplication .

**Comment by bigillu** [comment]
Removed the windows dependencies
Changed the entry point to python as opposed to running the shell script
